[package]
name = "dsp-stuff-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
darling = "0.14.0"
proc-macro2 = "1.0.37"
quote = "1.0.18"
syn = "1.0.91"
